language: python
python:
- '3.7'
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  provider: heroku
  app: devopstestelap
  api_key:
    secure: edG9B+8xiesdL+CxPsmBT+cNGTyjEIG34ATHgH5GBorf3swYOXPpA/Z2rsUNbNppV6XrN5hQMdDmqTV0kYP78AtYtZGqiZAMFAgiUAUhdsD2LMET3weQ2IzFgmws9MlAftR0xCp5oDhRMTARppxKNh/ymzX1p/huA95gcAKRK2mjkHvcXsubYuGo/LZISj2tAaCZegpDw5qXAyjs9enximPBt1D5io/NNnVv4PN/1zGfNqYgB/Hp9EFkhl2tktQKp/fQSHgn930X7e/s/1mN4hb44KHUNYa6lBB4UeegZkriVlHpXXsUEFTKzyU5zVp32mfdcTRmB4hHtS956j0Huz/fSCccLHI4JdII6Y+NLN44/i3Rite204Xo9MPXJ6aAbH2yjRy6rNiDyXYqXlXNgrg1v4/CtN68/zouQ//TnWs+Y5QHybMYvJpBOrAGbpF8JSpJ65EJy1UpALNpAL2bWLiUnLxFbCSGG0i/8n6pXA/M9zcW+dEHfPIc8Ov7VC60E62uKdD3N9EKXIDXzgFZ6+BkWKuAsnVvexOc59LDDyM9EZ1RUab4NF5d0HWW8+dxlJfXjBYFHaXXav0GjjDvpWk9egD5kI85uhPMZrrHSzSxRMFk2P+gJTkfHmGtNjTeR1vyY8She1zktz5M8rzFh+bLCGmvP/8GMUEb3e2zdFM=
