language: python
python:
- '3.7'
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  provider: heroku
  app: devopstestelap
    api_key:
    secure: nTJiAI5XCZcDzuXdrodsPUeehxkDrJF9uNb+EqyMUOsX+kofpbMQUuU7FNKvIcQIiz7NfL3KFo2MMepAUFIgC5QvvkIxwRX1fjeABdf224w0STdr4M9VXdWmmx/o7FbRKnQKOwPsuH/M++4OSSiWVn19yo3GZaM8Kx41+jqIhjXLMzFJzmxESSiuYzd8uM1dKCg9cWwA7wlwpQHUyLCfpUJR6Tc1YOT/V2eNVAGQuMtDsWvzJjBJ4/BvdGDCvtLgqDRAAwKvHWwZUt/vzCepU8wbCU9n0Qlj1U03HAr5GHM0zj6zNBHywuuHlfekbytXKnV05WPO8R2qZ6d7VvzgRyBcjyTbo7JoVuuSMASTMbRe0h4mJFfHYQ4p5rY5DraMwKkTNjHDtc4/KTnMpPLxpK8QO8Rmdkq7l2FGGdtgDGjhp9aoQVi1ESp3Ua6Pqnv1VKpXoPQcwb4i9ot+1ZX4ESezMoSScdArAj/kA8uB9oiiLhvYCtYZIhAEjQ6lciO6NkesqJqnEYgnUBgW+eZRKDt27ML+rSaksIWkv42tdPNkKzcrn7AWTMwC1KD0k7kNq0evNueUmh9siIKqRyfhNP8V8OsIOkLNk8ikdxiJV13VE/ZxPuyNqs3/ke+U20GQBC7POFQ86Q88SJxlaOffgdTIzm05XiYyZWfDwGWyCTo=
